version: '3.5'

services:

  frontend:
    image: mingdatacom/frontend:latest
    container_name: angulartest-frontend
#    build:
#      context: .
#      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '8082:80'